### ISSUE TITLE
Generator expression must be parenthesized

### ISSUE THREAD

**Issue by YorozuyaDev** [robinhood/thorn#40]
I am currently using python 3.8, Django 3.0.2 thorn 1.5.2 in Arch Linux. When I try to import thorn to my script it returns following error:
```
Traceback (most recent call last):
  File "authbot.py", line 10, in <module>
    from thorn import ModelEvent, webhook_model
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/thorn/__init__.py", line 9, in <module>
    from .events import Event, ModelEvent
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/thorn/events.py", line 282
    '__now_' in k for k in keys(self.filter_fields),
    ^
SyntaxError: Generator expression must be parenthesized
```

**Comment by camrail** [comment]
Had the same issue, looks like this only works with python 3.6 at present

**Comment by LikoIlya** [comment]
Same for me(

**Comment by aadithpm** [comment]
Currently building something with Python 3.6, Django 1.10 and Django REST Framework 3.8.2. I stuck with 1.10 since that seems to be the last documented version that they said they support.

I do eventually plan to move away from this though since I'm not sure how development looks down the line for this.

**Comment by camrail** [comment]
> Currently building something with Python 3.6, Django 1.10 and Django REST Framework 3.8.2. I stuck with 1.10 since that seems to be the last documented version that they said they support.
> 
> I do eventually plan to move away from this though since I'm not sure how development looks down the line for this.

I am using Django 2.0.1 and it's working okay

**Comment by aadithpm** [comment]
> > Currently building something with Python 3.6, Django 1.10 and Django REST Framework 3.8.2. I stuck with 1.10 since that seems to be the last documented version that they said they support.
> > I do eventually plan to move away from this though since I'm not sure how development looks down the line for this.
> 
> I am using Django 2.0.1 and it's working okay

Ah, thanks for the information. I'll try updating and check if it doesn't break anything else.

**Comment by ardoshi** [comment]
Hello,
I'm using Python 3.9.0, Django 3.1.3 and Django Rest Framework 3.12.2
I am unable to resolve the following error:

 __File "\site-packages\thorn\_state.py", line 6, in <module>
    from vine.five import monotonic
ModuleNotFoundError: No module named 'vine.five'__

Is there some way to solve this other than going lower on all the versions?
